RewriteEngine On
RewriteRule ^/scrapper$ /scrapper/ [R=301,L]

ProxyPreserveHost On
RequestHeader set X-Forwarded-Prefix "/scrapper"
RequestHeader set X-Forwarded-Proto expr=%{REQUEST_SCHEME}
RequestHeader set X-Forwarded-Host expr=%{HTTP_HOST}

ProxyPass /scrapper/ http://127.0.0.1:8080/
ProxyPassReverse /scrapper/ http://127.0.0.1:8080/
