server {
    listen 80;
    listen [::]:80;
    server_name www.euwt.eu;

    client_max_body_size 10m;

    location = /scrapper {
        return 301 /scrapper/;
    }

    location /scrapper/ {
        rewrite ^/scrapper(/.*)$ $1 break;
        include proxy_params;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Prefix /scrapper;
        proxy_pass http://unix:/var/www/scrapper/scrapper.sock;
        proxy_read_timeout 60s;
    }
}
